version: '3.8'

services:
  order-service:
    build:
      context: ../order-service/order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - payment-service
      - invoice-service

  payment-service:
    build:
      context: ../payment-service/payment-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  invoice-service:
    build:
      context: ../invoice-service/invoice-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      
  app-gateway:
    build:
      context: ../app-gateway/app-gateway
    ports:
      - "8083:8080"
    depends_on:
      - order-service
      - payment-service
      - invoice-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
