spring:
  application:
    name: invoice-service
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: invoice-service
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
