apiVersion: v1
kind: Service
metadata:
  name: app-gateway
spec:
  type: NodePort
  selector:
    app: app-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30803