apiVersion: v1
kind: Service
metadata:
  name: invoice-service
spec:
  type: NodePort
  selector:
    app: invoice-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30802